// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { jsx, jsxs, Fragment } from 'react/jsx-runtime';
import { Placeholder, NextImage, Text, Link, CdpHelper, useSitecore } from '@sitecore-content-sdk/nextjs';
import { forwardRef, useEffect } from 'react';
import React from 'react';
import { CompatibleLink } from 'components/content-sdk/CompatibleLink';
import { getFieldValue } from 'lib/component-props';
import Head from 'next/head';
import client from 'lib/sitecore-client';
import Image from 'next/image';
import * as FEAAS from '@sitecore-feaas/clientside/react';
import nextConfig from 'next.config';
import NextLink from 'next/link';
import { pageView } from '@sitecore-content-sdk/events';
import config from 'sitecore.config';

const importMap = [
  {
    module: 'react/jsx-runtime',
    exports: [
      { name: 'jsx', value: jsx },
      { name: 'jsxs', value: jsxs },
      { name: 'Fragment', value: Fragment },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Placeholder', value: Placeholder },
      { name: 'NextImage', value: NextImage },
      { name: 'Text', value: Text },
      { name: 'Link', value: Link },
      { name: 'CdpHelper', value: CdpHelper },
      { name: 'useSitecore', value: useSitecore },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'forwardRef', value: forwardRef },
      { name: 'useEffect', value: useEffect },
      { name: 'default', value: React },
    ]
  },
  {
    module: 'components/content-sdk/CompatibleLink',
    exports: [
      { name: 'CompatibleLink', value: CompatibleLink },
    ]
  },
  {
    module: 'lib/component-props',
    exports: [
      { name: 'getFieldValue', value: getFieldValue },
    ]
  },
  {
    module: 'next/head',
    exports: [
      { name: 'default', value: Head },
    ]
  },
  {
    module: 'lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image },
    ]
  },
  {
    module: '@sitecore-feaas/clientside/react',
    exports: [
      { name: '*', value: FEAAS },
    ]
  },
  {
    module: 'next.config',
    exports: [
      { name: 'default', value: nextConfig },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: NextLink },
    ]
  },
  {
    module: '@sitecore-content-sdk/events',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultImportEntries, importMap);
